export { registerSettingsHandlers, type IpcMainLike } from './settings-handlers'
export { registerShellHandlers, type OpenExternal } from './shell-handlers'
export { registerLicenseHandlers } from './license-handlers'
export { registerProfileHandlers } from './profile-handlers'
export { registerProxyHandlers } from './proxy-handlers'
export { registerContentTemplateHandlers } from './content-template-handlers'
export { registerAutomationHandlers } from './automation-handlers'
