"""add_token_lifecycle_fields

Revision ID: 53457421ab4c
Revises: 20260329_02
Create Date: 2026-04-05 15:44:35.512887
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '53457421ab4c'
down_revision: Union[str, Sequence[str], None] = '20260329_02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facebook_pages', sa.Column('token_type', sa.Enum('short_lived', 'long_lived', 'system_user', name='tokentype'), nullable=False))
    op.add_column('facebook_pages', sa.Column('token_expires_at', sa.DateTime(), nullable=True))
    op.add_column('facebook_pages', sa.Column('token_last_checked_at', sa.DateTime(), nullable=True))
    op.add_column('facebook_pages', sa.Column('token_health_status', sa.String(), nullable=False))
    op.drop_constraint(op.f('facebook_pages_page_id_key'), 'facebook_pages', type_='unique')
    op.drop_index(op.f('ix_facebook_pages_page_id'), table_name='facebook_pages')
    op.create_index(op.f('ix_facebook_pages_page_id'), 'facebook_pages', ['page_id'], unique=True)
    op.drop_constraint(op.f('interactions_log_page_id_fkey'), 'interactions_log', type_='foreignkey')
    op.create_foreign_key(None, 'interactions_log', 'facebook_pages', ['page_id'], ['page_id'], ondelete='SET NULL')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_constraint(op.f('videos_campaign_id_fkey'), 'videos', type_='foreignkey')
    op.create_foreign_key(None, 'videos', 'campaigns', ['campaign_id'], ['id'], ondelete='CASCADE')
    op.alter_column('worker_heartbeats', 'worker_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('worker_heartbeats_worker_name_key'), 'worker_heartbeats', type_='unique')
    op.drop_index(op.f('ix_worker_heartbeats_worker_name'), table_name='worker_heartbeats')
    op.create_index(op.f('ix_worker_heartbeats_worker_name'), 'worker_heartbeats', ['worker_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_heartbeats_worker_name'), table_name='worker_heartbeats')
    op.create_index(op.f('ix_worker_heartbeats_worker_name'), 'worker_heartbeats', ['worker_name'], unique=False)
    op.create_unique_constraint(op.f('worker_heartbeats_worker_name_key'), 'worker_heartbeats', ['worker_name'], postgresql_nulls_not_distinct=False)
    op.alter_column('worker_heartbeats', 'worker_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.create_foreign_key(op.f('videos_campaign_id_fkey'), 'videos', 'campaigns', ['campaign_id'], ['id'])
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'interactions_log', type_='foreignkey')
    op.create_foreign_key(op.f('interactions_log_page_id_fkey'), 'interactions_log', 'facebook_pages', ['page_id'], ['page_id'])
    op.drop_index(op.f('ix_facebook_pages_page_id'), table_name='facebook_pages')
    op.create_index(op.f('ix_facebook_pages_page_id'), 'facebook_pages', ['page_id'], unique=False)
    op.create_unique_constraint(op.f('facebook_pages_page_id_key'), 'facebook_pages', ['page_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('facebook_pages', 'token_health_status')
    op.drop_column('facebook_pages', 'token_last_checked_at')
    op.drop_column('facebook_pages', 'token_expires_at')
    op.drop_column('facebook_pages', 'token_type')
    # ### end Alembic commands ###
