"""add_token_lifecycle_fields

Revision ID: 53457421ab4c
Revises: 20260329_02
Create Date: 2026-04-05 15:44:35.512887
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '53457421ab4c'
down_revision: Union[str, Sequence[str], None] = '20260329_02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    from sqlalchemy.engine.reflection import Inspector
    inspector = Inspector.from_engine(bind)
    
    sa.Enum('short_lived', 'long_lived', 'system_user', name='tokentype').create(bind, checkfirst=True)
    
    fb_columns = [col['name'] for col in inspector.get_columns('facebook_pages')]
    if 'token_type' not in fb_columns:
        op.add_column('facebook_pages', sa.Column('token_type', sa.Enum('short_lived', 'long_lived', 'system_user', name='tokentype'), nullable=False, server_default=sa.text("'long_lived'")))
    if 'token_expires_at' not in fb_columns:
        op.add_column('facebook_pages', sa.Column('token_expires_at', sa.DateTime(), nullable=True))
    if 'token_last_checked_at' not in fb_columns:
        op.add_column('facebook_pages', sa.Column('token_last_checked_at', sa.DateTime(), nullable=True))
    if 'token_health_status' not in fb_columns:
        op.add_column('facebook_pages', sa.Column('token_health_status', sa.String(), nullable=False, server_default=sa.text("'unknown'")))
        
    fk_constraints = [fk['name'] for fk in inspector.get_foreign_keys('interactions_log')]
    if 'interactions_log_page_id_fkey' in fk_constraints:
        op.drop_constraint(op.f('interactions_log_page_id_fkey'), 'interactions_log', type_='foreignkey')
    
    uq_constraints = [uq['name'] for uq in inspector.get_unique_constraints('facebook_pages')]
    if 'facebook_pages_page_id_key' in uq_constraints:
        op.drop_constraint(op.f('facebook_pages_page_id_key'), 'facebook_pages', type_='unique')
        
    indexes = [ix['name'] for ix in inspector.get_indexes('facebook_pages')]
    if 'ix_facebook_pages_page_id' in indexes:
        op.drop_index(op.f('ix_facebook_pages_page_id'), table_name='facebook_pages')
        
    op.create_index(op.f('ix_facebook_pages_page_id'), 'facebook_pages', ['page_id'], unique=True)
    
    if 'fk_interactions_log_page_id_set_null' not in fk_constraints:
        op.create_foreign_key('fk_interactions_log_page_id_set_null', 'interactions_log', 'facebook_pages', ['page_id'], ['page_id'], ondelete='SET NULL')
        
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
               
    user_uq = [uq['name'] for uq in inspector.get_unique_constraints('users')]
    if 'users_username_key' in user_uq:
        op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
        
    user_ix = [ix['name'] for ix in inspector.get_indexes('users')]
    if 'ix_users_username' in user_ix:
        op.drop_index(op.f('ix_users_username'), table_name='users')
        
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    
    video_fk = [fk['name'] for fk in inspector.get_foreign_keys('videos')]
    if 'videos_campaign_id_fkey' in video_fk:
        op.drop_constraint(op.f('videos_campaign_id_fkey'), 'videos', type_='foreignkey')
        
    if 'fk_videos_campaign_id_cascade' not in video_fk:
        op.create_foreign_key('fk_videos_campaign_id_cascade', 'videos', 'campaigns', ['campaign_id'], ['id'], ondelete='CASCADE')
        
    op.alter_column('worker_heartbeats', 'worker_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
               
    wh_uq = [uq['name'] for uq in inspector.get_unique_constraints('worker_heartbeats')]
    if 'worker_heartbeats_worker_name_key' in wh_uq:
        op.drop_constraint(op.f('worker_heartbeats_worker_name_key'), 'worker_heartbeats', type_='unique')
        
    wh_ix = [ix['name'] for ix in inspector.get_indexes('worker_heartbeats')]
    if 'ix_worker_heartbeats_worker_name' in wh_ix:
        op.drop_index(op.f('ix_worker_heartbeats_worker_name'), table_name='worker_heartbeats')
        
    op.create_index(op.f('ix_worker_heartbeats_worker_name'), 'worker_heartbeats', ['worker_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_heartbeats_worker_name'), table_name='worker_heartbeats')
    op.create_index(op.f('ix_worker_heartbeats_worker_name'), 'worker_heartbeats', ['worker_name'], unique=False)
    op.create_unique_constraint(op.f('worker_heartbeats_worker_name_key'), 'worker_heartbeats', ['worker_name'], postgresql_nulls_not_distinct=False)
    op.alter_column('worker_heartbeats', 'worker_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # H5: Dùng tên constraint tường minh thay vì None (None gây ProgrammingError trên PostgreSQL)
    op.drop_constraint('fk_videos_campaign_id_cascade', 'videos', type_='foreignkey')
    op.create_foreign_key(op.f('videos_campaign_id_fkey'), 'videos', 'campaigns', ['campaign_id'], ['id'])
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('fk_interactions_log_page_id_set_null', 'interactions_log', type_='foreignkey')
    op.create_foreign_key(op.f('interactions_log_page_id_fkey'), 'interactions_log', 'facebook_pages', ['page_id'], ['page_id'])
    op.drop_index(op.f('ix_facebook_pages_page_id'), table_name='facebook_pages')
    op.create_index(op.f('ix_facebook_pages_page_id'), 'facebook_pages', ['page_id'], unique=False)
    op.create_unique_constraint(op.f('facebook_pages_page_id_key'), 'facebook_pages', ['page_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('facebook_pages', 'token_health_status')
    op.drop_column('facebook_pages', 'token_last_checked_at')
    op.drop_column('facebook_pages', 'token_expires_at')
    op.drop_column('facebook_pages', 'token_type')
    # L1: Drop PostgreSQL Enum type 'tokentype' — không drop thì upgrade lại sau sẽ fail
    sa.Enum(name='tokentype').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
