"""add_organizations_table_and_relationships

Revision ID: 93640c6447c0
Revises: c14f91eae2aa
Create Date: 2026-05-05 13:02:31.931332
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '93640c6447c0'
down_revision: Union[str, Sequence[str], None] = 'c14f91eae2aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    
    op.add_column('campaigns', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'campaigns', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    
    op.add_column('facebook_pages', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'facebook_pages', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    
    op.add_column('users', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    
    op.add_column('videos', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'videos', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    
    op.add_column('interactions_log', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'interactions_log', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    
    op.add_column('task_queue', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'task_queue', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    
    op.add_column('system_events', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'system_events', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'system_events', type_='foreignkey')
    op.drop_column('system_events', 'organization_id')
    
    op.drop_constraint(None, 'task_queue', type_='foreignkey')
    op.drop_column('task_queue', 'organization_id')
    
    op.drop_constraint(None, 'interactions_log', type_='foreignkey')
    op.drop_column('interactions_log', 'organization_id')
    
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.drop_column('videos', 'organization_id')
    
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'organization_id')
    
    op.drop_constraint(None, 'facebook_pages', type_='foreignkey')
    op.drop_column('facebook_pages', 'organization_id')
    
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_column('campaigns', 'organization_id')
    
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
