"""update user schema

Revision ID: c14f91eae2aa
Revises: 20260506_02
Create Date: 2026-05-04 13:07:38.368524
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'c14f91eae2aa'
down_revision: Union[str, Sequence[str], None] = '20260506_02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Kiểm tra xem bảng users có tồn tại không
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    op.execute('DROP TYPE IF EXISTS userrole CASCADE')
    op.execute("CREATE TYPE userrole AS ENUM ('super_admin', 'owner', 'editor', 'viewer')")
    userrole_enum = postgresql.ENUM('super_admin', 'owner', 'editor', 'viewer', name='userrole', create_type=False)

    if 'users' in tables:
        # Rename bảng cũ để backup nếu chưa có users_old
        if 'users_old' not in tables:
            op.execute('ALTER TABLE users RENAME TO users_old')
        else:
            op.execute('DROP TABLE users') # Nếu đã có backup thì xóa bảng hiện tại để tạo mới

    op.create_table(
        'users',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('full_name', sa.String(), nullable=True),
        sa.Column('hashed_password', sa.String(), nullable=False),
        sa.Column('role', userrole_enum, nullable=False, server_default='viewer'),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')),
        sa.Column('avatar_url', sa.String(), nullable=True),
        sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default=sa.text('false')),
        sa.Column('last_login_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP')),
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    
    if 'users_old' in tables:
        # Migrating data from users_old to users (ánh xạ username -> email)
        # Kiểm tra xem bảng cũ có cột username không
        columns = [c['name'] for c in inspector.get_columns('users_old')]
        if 'username' in columns:
            op.execute(
                "INSERT INTO users (id, email, full_name, hashed_password, role, is_active, created_at, updated_at) "
                "SELECT id, username || '@example.com', display_name, password_hash, 'viewer', is_active, now(), now() FROM users_old"
            )
        # op.drop_table('users_old') # Keep backup to prevent data loss

    from app.core.config import settings
    from passlib.context import CryptContext
    import uuid
    pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")
    
    root_email = settings.ROOT_ADMIN_EMAIL
    hashed_pwd = pwd_context.hash(settings.ROOT_ADMIN_PASSWORD)
    
    op.execute(
        f"INSERT INTO users (id, email, hashed_password, role, is_active, created_at, updated_at) "
        f"SELECT '{uuid.uuid4()}', '{root_email}', '{hashed_pwd}', 'super_admin', true, now(), now() "
        f"WHERE NOT EXISTS (SELECT 1 FROM users WHERE email = '{root_email}')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.execute('DROP TYPE IF EXISTS userrole CASCADE')
    # ### end Alembic commands ###
