"""add_org_id_to_all_models

Revision ID: efafd81dbbc7
Revises: 93640c6447c0
Create Date: 2026-05-05 13:59:54.236498
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'efafd81dbbc7'
down_revision: Union[str, Sequence[str], None] = '93640c6447c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('facebook_pages', 'token_type',
               existing_type=postgresql.ENUM('short_lived', 'long_lived', 'system_user', name='tokentype'),
               nullable=True,
               existing_server_default=sa.text("'long_lived'::tokentype"))
    op.drop_constraint(op.f('facebook_pages_page_id_key'), 'facebook_pages', type_='unique')
    op.drop_index(op.f('ix_facebook_pages_page_id'), table_name='facebook_pages')
    op.create_index(op.f('ix_facebook_pages_page_id'), 'facebook_pages', ['page_id'], unique=True)
    op.drop_constraint(op.f('interactions_log_page_id_fkey'), 'interactions_log', type_='foreignkey')
    op.create_foreign_key(None, 'interactions_log', 'facebook_pages', ['page_id'], ['page_id'], ondelete='SET NULL')
    op.add_column('system_events', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'system_events', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.add_column('task_queue', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.add_column('task_queue', sa.Column('category', sa.String(), nullable=True))
    op.drop_index(op.f('ix_task_queue_task_type'), table_name='task_queue')
    op.create_index(op.f('ix_task_queue_category'), 'task_queue', ['category'], unique=False)
    op.create_foreign_key(None, 'task_queue', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_column('task_queue', 'task_type')
    op.drop_constraint(op.f('users_organization_id_fkey'), 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('videos_campaign_id_fkey'), 'videos', type_='foreignkey')
    op.create_foreign_key(None, 'videos', 'campaigns', ['campaign_id'], ['id'], ondelete='CASCADE')
    op.alter_column('worker_heartbeats', 'worker_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('worker_heartbeats_worker_name_key'), 'worker_heartbeats', type_='unique')
    op.drop_index(op.f('ix_worker_heartbeats_worker_name'), table_name='worker_heartbeats')
    op.create_index(op.f('ix_worker_heartbeats_worker_name'), 'worker_heartbeats', ['worker_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_worker_heartbeats_worker_name'), table_name='worker_heartbeats')
    op.create_index(op.f('ix_worker_heartbeats_worker_name'), 'worker_heartbeats', ['worker_name'], unique=False)
    op.create_unique_constraint(op.f('worker_heartbeats_worker_name_key'), 'worker_heartbeats', ['worker_name'], postgresql_nulls_not_distinct=False)
    op.alter_column('worker_heartbeats', 'worker_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.create_foreign_key(op.f('videos_campaign_id_fkey'), 'videos', 'campaigns', ['campaign_id'], ['id'])
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key(op.f('users_organization_id_fkey'), 'users', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    op.add_column('task_queue', sa.Column('task_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'task_queue', type_='foreignkey')
    op.drop_index(op.f('ix_task_queue_category'), table_name='task_queue')
    op.create_index(op.f('ix_task_queue_task_type'), 'task_queue', ['task_type'], unique=False)
    op.drop_column('task_queue', 'category')
    op.drop_column('task_queue', 'organization_id')
    op.drop_constraint(None, 'system_events', type_='foreignkey')
    op.drop_column('system_events', 'organization_id')
    op.drop_constraint(None, 'interactions_log', type_='foreignkey')
    op.create_foreign_key(op.f('interactions_log_page_id_fkey'), 'interactions_log', 'facebook_pages', ['page_id'], ['page_id'])
    op.drop_index(op.f('ix_facebook_pages_page_id'), table_name='facebook_pages')
    op.create_index(op.f('ix_facebook_pages_page_id'), 'facebook_pages', ['page_id'], unique=False)
    op.create_unique_constraint(op.f('facebook_pages_page_id_key'), 'facebook_pages', ['page_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('facebook_pages', 'token_type',
               existing_type=postgresql.ENUM('short_lived', 'long_lived', 'system_user', name='tokentype'),
               nullable=False,
               existing_server_default=sa.text("'long_lived'::tokentype"))
    # ### end Alembic commands ###
